WARD_INFO = [
	[["Ainslie"],["Paul"],[43],["Scarborough East"]],
	[["Di Ciano"],["Justin"],[5],["Etobicoke-Lakeshore"]],
	[["McConnell"],["Pam"],[28],["Toronto Centre-Rosedale"]],
	[["Augimeri"],["Maria"],[9],["York Centre"]],
	[["Di Giorgio"],["Frank"],[12],["York South-Weston"]],
	[["McMahon"],["Mary-Margaret"],[32],["Beaches-East York"]],
	[["Bailão"],["Ana"],[18],["Davenport"]],
	[["Doucette"],["Sarah"],[13],["Parkdale-High Park"]],
	[["Mihevc"],["Joe"],[21],["St. Paul's"]],
	[["Berardinetti"],["Michelle"],[35],["Scarborough Southwest"]],
	[["Filion"],["John"],[23],["Willowdale"]],
	[["Minnan-Wong"],["Denzil"],[34],["Don Valley East"]],
	[["Burnside"],["Jon"],[26],["Don Valley West"]],
	[["Fletcher"],["Paula"],[30],["Toronto-Danforth"]],
	[["Moeser"],["Ron"],[44],["Scarborough East"]],
	[["Campbell"],["John"],[4],["Etobicoke Centre"]],
	[["Ford"],["Rob"],[2],["Etobicoke North"]],
	[["Nunziata"],["Frances"],[11],["York South-Weston"]],
	[["Carmichael Greb"],["Christin"],[16],["Eglinton-Lawrence"]],
	[["Fragedakis"],["Mary"],[29],["Toronto-Danforth"]],
	[["Palacio"],["Cesar"],[17],["Davenport"]],
	[["Carroll"],["Shelley"],[33],["Don Valley East"]],
	[["Grimes"],["Mark"],[6],["Etobicoke-Lakeshore"]],
	[["Pasternak"],["James"],[10],["York Centre"]],
	[["Cho"],["Raymond"],[42],["Scarborough-Rouge River"]],
	[["Holyday"],["Stephen"],[3],["Etobicoke Centre"]],
	[["Perks"],["Gord"],[14],["Parkdale-High Park"]],
	[["Colle"],["Josh"],[15],["Eglinton-Lawrence"]],
	[["Karygiannis"],["Jim"],[39],["Scarborough-Agincourt"]],
	[["Perruzza"],["Anthony"],[8],["York West"]],
	[["Crawford"],["Gary"],[36],["Scarborough Southwest"]],
	[["Kelly"],["Norm"],[40],["Scarborough-Agincourt"]],
	[["Robinson"],["Jaye"],[25],["Don Valley West"]],
	[["Cressy"],["Joe"],[20],["Trinity-Spadina"]],
	[["Layton"],["Mike"],[19],["Trinity-Spadina"]],
	[["Shiner"],["David"],[24],["Willowdale"]],
	[["Crisanti"],["Vincent"],[1],["Etobicoke North"]],
	[["Lee"],["Chin"],[41],["Scarborough-Rouge River"]],
	[["Thompson"],["Michael"],[37],["Scarborough Centre"]],
	[["Davis"],["Janet"],[31],["Beaches-East York"]],
	[["Mammoliti"],["Giorgio"],[7],["York West"]],
	[["Wong-Tam"],["Kristyn"],[27],["Toronto Centre-Rosedale"]],
	[["De Baeremaeker"],["Glenn"],[38],["Scarborough Centre"]],
	[["Matlow"],["Josh"],[22],["St. Paul's"]]
]